### ISSUE TITLE
Users can upload and validate their datasetdescriptions for testing purposes before publicating the definitive datacatalog-URL

### ISSUE THREAD

**Issue by faina007** [netwerk-digitaal-erfgoed/dataset-register#740]
With this feature users can check the validity of their datasetdescription for testing purposes. The results of such a test can be used as input for a programmar who developes the final URL for the datasetdescription.

**Comment by coret** [comment]
The current means to validate a datasetdescription include:
- Using [Apache Jena SHACL](https://jena.apache.org/documentation/shacl/) CLI tool, use https://raw.githubusercontent.com/netwerk-digitaal-erfgoed/dataset-register/main/shacl/register.ttl as shape file (URL or `wget `the file for local use).
- Using the `/datasets/validate` method of the [Datasetregister API](https://datasetregister.netwerkdigitaalerfgoed.nl/api/static/index.html) - note this requires the datasetdescription to be available online as an URI has to be specified as parameter of this method call.
- Using the [validation page of the demonstrator](https://datasetregister.netwerkdigitaalerfgoed.nl/validate.php) - this page calls the API as described in the previous bullet, so also requires an URI.

The requested additional means of validating would not require the datasetdescription to be online already. It is a variation of the `/datasets/validate` method which take the complete datasetdescription RDF as input (instead of URI). This extra API method could also be added in the demonstrator interface.
